import type { FC } from 'react';
import Hero from '@/components/Hero';
import BlogItem from '@/app/(blog)/BlogItem';
import BlogFilter from '@/app/(blog)/BlogFilter';
import HeroImage from '@/public/hero.webp';
import { db } from '@/lib/db';

export const metadata = {
  title: 'Hello bro',
  description: 'Generated by create next app',
};

interface Props {
  searchParams?: {
    search?: string;
    category?: string;
    tags?: string[];
  };
}

const Home: FC<Props> = async ({ searchParams }) => {
  const posts = await db.post.findMany({
    include: {
      author: true,
      _count: {
        select: { comments: true, likes: true },
      },
    },
  });

  return (
    <main>
      <Hero image={HeroImage}>
        <h1 className="mb-4 font-display text-4xl leading-none text-white md:text-5xl lg:text-6xl">
          Vivencias en la selvita
        </h1>
        <p className="text-white">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque
          enim orci, mollis ac nulla eget, vulputate dignissim libero.
        </p>
      </Hero>

      <div className="mx-auto max-w-7xl px-6 pt-10 md:pt-12 lg:pt-16 xl:pt-20">
        {/* <div className="flex items-center justify-between">
          <h2 className="font-display">Diario en la Selvita</h2>
          <BlogFilter />
        </div> */}

        <div className="grid grid-cols-1 gap-10 pt-8 md:grid-cols-2 md:pt-10 lg:pt-12 xl:pt-14">
          {posts.map((post) => (
            <BlogItem key={post.id} post={post} />
          ))}
        </div>
      </div>
    </main>
  );
};

export default Home;
