import type { FC } from 'react';
import Hero from '@/components/Hero';
import BlogItem from '@/app/(blog)/BlogItem';
import BlogFilter from '@/app/(blog)/BlogFilter';
import HeroImage from '@/public/hero.webp';
import { db } from '@/lib/db';

export const metadata = {
  title: 'Hello bro',
  description: 'Generated by create next app',
};

interface Props {
  searchParams?: {
    search?: string;
    category?: string;
    tags?: string[];
  };
}

const Home: FC<Props> = async ({ searchParams }) => {
  const posts = await db.post.findMany({
    include: {
      author: true,
      _count: {
        select: { comments: true, likes: true },
      },
    },
  });

  return (
    <main>
      <Hero image={HeroImage}>
        <h1 className="mb-4 font-display text-5xl leading-none text-white md:text-6xl lg:text-6.5xl">
          Vivencias en la selvita
        </h1>
        <p className="text-sm text-white md:text-base">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque
          enim orci, mollis ac nulla eget, vulputate dignissim libero.
        </p>
      </Hero>

      <div className="mx-auto max-w-7xl px-6 pt-14 md:pt-16 lg:pt-20 xl:pt-28">
        <div className="pb-8">
          <BlogFilter />
        </div>

        <div className="grid grid-cols-1 gap-10 md:grid-cols-2">
          {posts.map((post) => (
            <BlogItem key={post.id} post={post} />
          ))}
        </div>
      </div>
    </main>
  );
};

export default Home;
