import type { FC } from 'react';
import Hero from '@/components/Hero';
import BlogItem, { type Post } from './BlogItem';
import BaseButton from '@/components/ui/BaseButton';
import HeroImage from '@/public/hero.webp';
import BasePopover from '@/components/ui/BasePopover';

export const metadata = {
  title: 'Hello bro',
  description: 'Generated by create next app',
};

interface Props {
  searchParams?: {
    search?: string;
    category?: string;
    tags?: string[];
  };
}

const testPost: Post = {
  imageUrl: '/blog1.webp',
  title: 'Complete solution for your land & garden design',
  author: {
    fullname: 'Stefany Mariano',
    firstName: 'Stefany',
    lastName: 'Mariano',
    email: 'stefany@laselvitadeconcreto.com',
    id: 'jiasodgfkj',
  },
  comments: 2,
  likes: 5,
  date: '21 May',
  content:
    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor tellus sed lacus elementum elementum. Vivamus egestas neque sed eros venenatis, ut sollicitudin metus tempor. Curabitur auctor arcu est, et maximus neque aliquet nec. Aliquam in dolor eu tortor luctus auctor.</p> <p>Nullam scelerisque ante pellentesque, hendrerit ex id, porta lectus. Integer maximus lobortis purus eget ullamcorper. Mauris est erat, sollicitudin nec porta sit amet, lobortis at turpis. Phasellus ligula mauris, eleifend nec dictum ut, sagittis nec orci. Aenean ut commodo magna.</p>',
};

const anotherTestPost: Post = {
  imageUrl: '/blog2.webp',
  title: 'The environmental benefits of tower gardens',
  author: {
    fullname: 'Stefany Mariano',
    firstName: 'Stefany',
    lastName: 'Mariano',
    email: 'stefany@laselvitadeconcreto.com',
    id: 'jiasodgfkj',
  },
  comments: 7,
  likes: 34,
  date: '14 May',
  content:
    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor tellus sed lacus elementum elementum. Vivamus egestas neque sed eros venenatis, ut sollicitudin metus tempor. Curabitur auctor arcu est, et maximus neque aliquet nec. Aliquam in dolor eu tortor luctus auctor.</p> <p>Nullam scelerisque ante pellentesque, hendrerit ex id, porta lectus. Integer maximus lobortis purus eget ullamcorper. Mauris est erat, sollicitudin nec porta sit amet, lobortis at turpis. Phasellus ligula mauris, eleifend nec dictum ut, sagittis nec orci. Aenean ut commodo magna.</p>',
};

const Home: FC<Props> = ({ searchParams }) => {
  return (
    <main>
      <Hero image={HeroImage} />

      <div className="mx-auto max-w-7xl px-6 pt-10 md:pt-12 lg:pt-16 xl:pt-20">
        <div className="flex items-center justify-between">
          <h2 className="font-display">Diario en la Selvita</h2>
          <BasePopover />
        </div>

        <div className="grid grid-cols-1 gap-10 pt-8 md:grid-cols-2 md:pt-10 lg:pt-12 xl:pt-14">
          <BlogItem post={testPost} />
          <BlogItem post={anotherTestPost} />
        </div>
      </div>
    </main>
  );
};

export default Home;
