import { Poppins, Montserrat } from 'next/font/google';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

import './main.css';
import TopBar from '@/app/TopBar';
import Header from '@/app/Header';

const poppinsFont = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-poppins',
});

const montserratFont = Montserrat({
  subsets: ['latin'],
  weight: ['200', '400', '600'],
  variable: '--font-montserrat',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poppinsFont.variable} ${montserratFont.variable}`}
    >
      <body>
        <header>
          <TopBar />
          <Header />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
