import { Great_Vibes } from 'next/font/google';
import Hero from '@/components/layout/Hero';
import BlogFilter from '@/app/BlogFilter';

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'Hello bro',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main>
      <Hero>
        <h1
          className={`mb-4 text-4xl leading-none text-white md:text-6xl lg:text-7xl ${greatVibes.className}`}
        >
          La selvita de concreto
        </h1>
        <p className="text-white">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque
          enim orci, mollis ac nulla eget, vulputate dignissim libero. In a
          velit dui. Vestibulum sodales luctus volutpat. Etiam lobortis, urna id
          tristique ultricies, sapien risus consequat tortor, sit amet efficitur
          nisl nisi ac odio.
        </p>
      </Hero>

      <div className="mx-auto max-w-7xl px-6 pt-24">
        <BlogFilter />
      </div>
    </main>
  );
}
